//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.15 at 11:46:07 午後 CST 
//


package name.kghost.oauth.config;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the name.kghost.oauth.config.generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _OAuthUser_QNAME = new QName("", "OAuthUser");
    private final static QName _OAuthConsumer_QNAME = new QName("", "OAuthConsumer");
    private final static QName _OAuthConfig_QNAME = new QName("", "OAuthConfig");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: name.kghost.oauth.config.generated
     * 
     */
    public ObjectFactory() {
    	return;
    }

    /**
     * Create an instance of {@link OAuthConsumer }
     * 
     */
    public OAuthConsumer createOAuthConsumer() {
        return new OAuthConsumer(null, null, null);
    }

    /**
     * Create an instance of {@link OAuthUser }
     * 
     */
    public OAuthUser createOAuthUser() {
        return new OAuthUser(null, null);
    }

    /**
     * Create an instance of {@link OAuthConfig }
     * 
     */
    public OAuthConfig createOAuthConfig() {
        return new OAuthConfig();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OAuthUser }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "OAuthUser")
    public JAXBElement<OAuthUser> createOAuthUser(OAuthUser value) {
        return new JAXBElement<OAuthUser>(_OAuthUser_QNAME, OAuthUser.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OAuthConsumer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "OAuthConsumer")
    public JAXBElement<OAuthConsumer> createOAuthConsumer(OAuthConsumer value) {
        return new JAXBElement<OAuthConsumer>(_OAuthConsumer_QNAME, OAuthConsumer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OAuthConfig }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "OAuthConfig")
    public JAXBElement<OAuthConfig> createOAuthConfig(OAuthConfig value) {
        return new JAXBElement<OAuthConfig>(_OAuthConfig_QNAME, OAuthConfig.class, null, value);
    }

}
